### PR TITLE
Update README

### PR DESCRIPTION
**Pull request by Olshansk**
- Update some terminology
- Add details on zone and node count configurations
- Show an example on how to create a cluster using `gcloud`

### CODE REVIEW

**Review by Neutrollized — COMMENTED** [review]
I appreciate the PR, but no thanks.

First of all I already mentioned that `e2-micro` being not viable already...which essentially covers "micro" sized instances.

Secondly, this isn't a how-to on `gcloud` cli, it's a TF blueprint; and there's a lot more that goes into all those options than just a container clusters create command.

**Comment by Olshansk** [comment]
Thanks for the response! That makes complete sense.

I'll just create my own repo or a gist and link to your repo as a reference there.

**Comment by Neutrollized** [comment]
Definitely, @Olshansk!  You're more than welcome to do that.  Part of me not wanting to put the `glcoud` equivalent in the README is also for my own OCD-ness as I would then feel compelled to do the same for my other repos -_-"

Happy holidays!

**Comment by Olshansk** [comment]
For posterity, here is the gist: https://gist.github.com/Olshansk/63bd26e3ef9923fbd1ff2f49be1f0ae3

**Pull request closed without merging**
